[package]
name = "overlayplacer"
version = "1.0.0"
description = "AI 협업형 UI 레이아웃 배치 편집기"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-clipboard-manager = "2"

[profile.release]
strip = true
lto = true
codegen-units = 1
